### PR TITLE
Extended public keys support

### PR DESCRIPTION
**Pull request by darosior**
This:
- Renames the crate
- Updates to rust-bitcoin 0.24 :tada:
- Updates rust-miniscript to https://github.com/rust-bitcoin/rust-miniscript/pull/131 and move our Miniscripts to use `DescriptorPublicKey`s

### CODE REVIEW

**Comment by darosior** [comment]
Rebased after upstream rebased, and (painfully) rebased on #15 : i restored bisectability and went for a better API for descriptor while at it.

PSBT is now the next step to the :PSBTDESCRIPTORMINISCRIPTXPUBS: graal!

**Comment by darosior** [comment]
Rebased after latest upstream changes.

**Comment by darosior** [comment]
Rebased

**Comment by darosior** [comment]
Now that the upstream PR is merged, we run on upstream's master and no longer one of my branch (one step from the release!). This is now mergeable.

**Review by JSwambo — APPROVED** [review]
Ack dcb88a0b6cf482565b937f6ab84ea8932cab6343

**Pull request merged**
