### PR TITLE
transactions: derive Clone for RevaultTransaction s

### PR DESCRIPTION
**Pull request by darosior**
Reported-by: Jacob Swambo <jake.t.swambo@hotmail.co.uk>
Signed-off-by: Antoine Poinsot <darosior@protonmail.com>

### CODE REVIEW

**Comment by darosior** [comment]
This is a trivial change which i'd like not to have to rebase upon #10 (ie i'd like to merge soon) , @JSwambo could you have a quick look again ?

**Comment by JSwambo** [comment]
If you naively put `features = ["use-serde"]` in the cargo.toml for bitcoin, will serde's `#[derive(Serialize, Deserialize)]` work for the ravault tx types?

**Comment by darosior** [comment]
No, it's a newtype: i need to make it a trivial implem (not using #derive).

**Comment by darosior** [comment]
But that off the scope of this PR

**Review by JSwambo — APPROVED** [review]
tAck 4d6c943e2e87004b38203f4d40c23a44182337c5

**Pull request merged**
